import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# load data generated by data_csv.py. Adjust the path as necessary.
df = pd.read_csv('master_pioran_SANE_results.csv')

# Normalize column names just in case
rename_dict = {
    'α₁_median': 'alpha1', 'α₁': 'alpha1',
    'α₂_median': 'alpha2', 'α₂': 'alpha2',
    'r_high': 'r_high', 'R_high': 'r_high'
}
df = df.rename(columns=rename_dict)


df = df.sort_values(by='spin')

plt.figure(figsize=(9, 6.5))

sns.scatterplot(
    data=df,
    x='alpha1',
    y='alpha2',
    hue='spin',       
    style='r_high',   
    palette='coolwarm',
    s=110,            # Slightly larger points for readability
    alpha=0.85,
    edgecolor='black', # Clean borders around points makes overlapping dots stand out
    linewidth=0.6
)

plt.title(r'Accretion Flow Dynamics: Low-Frequency ($\alpha_1$) vs. High-Frequency ($\alpha_2$)', fontsize=13, pad=15)
plt.xlabel(r'Low-Frequency Index ($\alpha_1$)', fontsize=11)
plt.ylabel(r'High-Frequency Index ($\alpha_2$)', fontsize=11)

handles, labels = plt.gca().get_legend_handles_labels()

clean_labels = []
for label in labels:
    if label == 'spin':
        clean_labels.append(r'$\mathbf{Black\ Hole\ Spin\ (a)}$')
    elif label == 'r_high':
        clean_labels.append(r'$\mathbf{Thermodynamics\ (R_{high})}$')
        
    elif label in ['1', '1.0']:
        clean_labels.append(r'$R_{high} = 1$')
    elif label in ['10', '10.0']:
        clean_labels.append(r'$R_{high} = 10$')
    elif label in ['40', '40.0']:
        clean_labels.append(r'$R_{high} = 40$')
    elif label in ['160', '160.0']:
        clean_labels.append(r'$R_{high} = 160$')
    
        
    else:
        try:
            val = float(label)
            # Your exact spin values from your directory tree
            if val in [0.0, 0.5, -0.5, 15/16, -15/16]:
                clean_labels.append(f'a = {val:.4f}')
            else:
                # If it's a number but not a spin, it's an inclination angle from the point sizes
                clean_labels.append(f'$i = {int(val)}^\circ$')
        except ValueError:
            clean_labels.append(label)

plt.legend(handles, clean_labels, bbox_to_anchor=(1.02, 1), loc='upper left', frameon=True, borderaxespad=0)
plt.grid(True, alpha=0.3, linestyle='--')

plt.tight_layout()

# save plot
plt.savefig('SANE_data/alpha1_vs_alpha2_clean.png', bbox_inches='tight', dpi=300)
plt.show()