import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Load data generated by data_csv.py. Adjust the path as necessary.
df = pd.read_csv('master_pioran_results.csv')

rename_dict = {
    'α₁_median': 'alpha1', 'α₁': 'alpha1',
    'α₂_median': 'alpha2', 'α₂': 'alpha2',
    'f₁_median': 'f1_break', 'f1_break': 'f1_break',
    'f₁_stdev': 'f1_break_error', 'f1_err': 'f1_break_error',
    'R_high': 'r_high', 'r_high': 'r_high'
}
df = df.rename(columns=rename_dict)

df = df.sort_values(by='spin')

g = sns.FacetGrid(
    data=df, 
    col="r_high", 
    hue="spin", 
    palette="coolwarm", 
    height=5.5, 
    aspect=1.1,
    legend_out=True
)

g.map(
    plt.errorbar, 
    "inclination", 
    "f1_break", 
    "f1_break_error", 
    fmt='o',        
    capsize=4, 
    alpha=0.85,
    linewidth=1.5,
    markersize=6
)

g.set_axis_labels(r"Observer Inclination Angle ($i^\circ$)", r"Bending Frequency $f_1$ (Hz)", fontsize=11)

axes = g.axes.flatten()
print(axes)
axes[0].set_title(r"$R_{\mathrm{high}} = 1$", fontsize=12, pad=12)
axes[1].set_title(r"$R_{\mathrm{high}} = 10$", fontsize=12, pad=12)
axes[2].set_title(r"$R_{\mathrm{high}} = 40$", fontsize=12, pad=12)
axes[3].set_title(r"$R_{\mathrm{high}} = 160$", fontsize=12, pad=12)

for ax in axes:
    ax.set_yscale('log')
    # Force the X-axis ticks to match your exact simulation increments
    ax.set_xticks([30, 50, 70, 90, 110, 130, 150, 170])
    ax.grid(True, which="both", ls="--", alpha=0.3)


g.add_legend(title=r"$\mathbf{Black\ Hole\ Spin\ (a)}$", adjust_subtitles=True)

for text in g._legend.get_texts():
    try:
        val = float(text.get_text())
        text.set_text(f"a = {val:.4f}")
    except ValueError:
        pass

plt.tight_layout()
# Save the figure in a path you want
plt.savefig('MAD_data/f1_vs_inclination.png', bbox_inches='tight', dpi=300)
plt.show()