import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Setup paths and to data directories generated by your PIORAN/MCMC runs. Adjust the base_dir to your local environment.
base_dir = "/home/patrick/Bachelorproject/Pioran.jl/examples/ultranest/inference/SANE"

# Match the strings exactly with your folder/dictionary naming conventions
unique_spins = ['-15o16', '-1o2', '0', '+1o2', '+15o16'] 
r_high_values = [1, 10, 40, 160] 
inclinations = [10, 30, 50, 70, 90, 110, 130, 150, 170]

spin_titles = {
    '-15o16': r"Spin $a = -0.9375$ ($-\frac{15}{16}$)",
    '-1o2':   r"Spin $a = -0.5000$ ($-\frac{1}{2}$)",
    '0':      r"Spin $a = 0.0000$ (Non-spinning)",
    '+1o2':   r"Spin $a = +0.5000$ ($\frac{1}{2}$)",
    '+15o16': r"Spin $a = +0.9375$ ($\frac{15}{16}$)"
}

fig, axes = plt.subplots(1, 5, figsize=(22, 5), sharex=True, sharey=True)

palette = {
    1:   "#1b9e77", 
    10:  "#7570b3", 
    40:  "#d95f02", 
    160: "#e7298a"  
}

print("Starting PSD directory crawl...")

global_legend_handles = {}

# Loop through each spin state and plot the corresponding PSD curves for all R_high and inclination combinations
for s_idx, spin in enumerate(unique_spins):
    ax = axes[s_idx]
    
    # Walk through the sub-directories for this spin state
    for r_val in r_high_values:
        for inc in inclinations:
            
            # Match your folder naming convention
            folder_name = f"lc_Rh{r_val}_i{inc}.npz_single"
            file_path = os.path.join(base_dir, f"a{spin}", folder_name, "plots", "psd_ppc_data.txt")
            
            if os.path.exists(file_path):
                try:
                    # Load the whitespace/tab separated text data, ignoring the comment rows
                    raw_data = np.loadtxt(file_path, comments='#')
                    
                    # Row 0 is the frequency array (f)
                    frequencies = raw_data[0, :]
                    
                    median_psd = raw_data[4, :]
                    
                    line, = ax.loglog(
                        frequencies,
                        median_psd,
                        color=palette[r_val],
                        alpha=0.35, 
                        linewidth=1.2
                    )
                    
                    if r_val not in global_legend_handles:
                        global_legend_handles[r_val] = line
                        
                except Exception as e:
                    # Print errors during debugging if files fail to parse for reasons other than missing
                    # print(f"Error reading {file_path}: {e}")
                    pass

    # Styling
    title_text = spin_titles.get(spin, f"Spin $a = {spin}$")
    ax.set_title(title_text, fontsize=11, fontweight='bold', pad=12)
    ax.set_xlabel("Frequency (Hz)", fontsize=11)
    ax.grid(True, which="both", ls="--", alpha=0.3)
    
    if s_idx == 0:
        ax.set_ylabel("Power Spectral Density (PSD)", fontsize=11)

# Configure global legend outside the loop after all paths are checked
# This guarantees handles are captured regardless of which panel found them first
if global_legend_handles:
    sorted_rh_keys = sorted(global_legend_handles.keys())
    custom_lines = [global_legend_handles[k] for k in sorted_rh_keys]
    custom_labels = [r"$R_{\mathrm{high}} = " + f"{k}$" for k in sorted_rh_keys]
    
    # Place the legend on the first axis (or replace with fig.legend for a global one)
    leg = axes[0].legend(custom_lines, custom_labels, loc="lower left", frameon=True, facecolor='white', framealpha=0.9)
    for leg_line in leg.get_lines():
        leg_line.set_alpha(1.0)

plt.tight_layout()
# Save the figure in a path you want
plt.savefig('SANE_data/master_psd_per_spin.png', bbox_inches='tight', dpi=300)
print("Plot compiled and saved as 'master_psd_per_spin.png'!")
plt.show()